{"version":3,"names":["Object","defineProperty","exports","value","_AxiosError","_interopRequireDefault","require","_utils","e","__esModule","CanceledError","message","config","request","AxiosError","call","ERR_CANCELED","name","utils","inherits","__CANCEL__","_default"],"sources":["CanceledError.js"],"sourcesContent":["'use strict';\n\nimport AxiosError from '../core/AxiosError.js';\nimport utils from '../utils.js';\n\n/**\n * A `CanceledError` is an object that is thrown when an operation is canceled.\n *\n * @param {string=} message The message.\n * @param {Object=} config The config.\n * @param {Object=} request The request.\n *\n * @returns {CanceledError} The created error.\n */\nfunction CanceledError(message, config, request) {\n  // eslint-disable-next-line no-eq-null,eqeqeq\n  AxiosError.call(this, message == null ? 'canceled' : message, AxiosError.ERR_CANCELED, config, request);\n  this.name = 'CanceledError';\n}\n\nutils.inherits(CanceledError, AxiosError, {\n  __CANCEL__: true\n});\n\nexport default CanceledError;\n"],"mappings":"AAAA,YAAY;;AAACA,MAAA,CAAAC,cAAA,CAAAC,OAAA;EAAAC,KAAA;AAAA;AAAAD,OAAA;AAEb,IAAAE,WAAA,GAAAC,sBAAA,CAAAC,OAAA;AACA,IAAAC,MAAA,GAAAF,sBAAA,CAAAC,OAAA;AAAgC,SAAAD,uBAAAG,CAAA,WAAAA,CAAA,IAAAA,CAAA,CAAAC,UAAA,GAAAD,CAAA,gBAAAA,CAAA;AAEhC;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA,SAASE,aAAaA,CAACC,OAAO,EAAEC,MAAM,EAAEC,OAAO,EAAE;EAC/C;EACAC,sBAAU,CAACC,IAAI,CAAC,IAAI,EAAEJ,OAAO,IAAI,IAAI,GAAG,UAAU,GAAGA,OAAO,EAAEG,sBAAU,CAACE,YAAY,EAAEJ,MAAM,EAAEC,OAAO,CAAC;EACvG,IAAI,CAACI,IAAI,GAAG,eAAe;AAC7B;AAEAC,iBAAK,CAACC,QAAQ,CAACT,aAAa,EAAEI,sBAAU,EAAE;EACxCM,UAAU,EAAE;AACd,CAAC,CAAC;AAAC,IAAAC,QAAA,GAAAnB,OAAA,cAEYQ,aAAa","ignoreList":[]}